hosts:
- repository: NIDAP-Community/demo-syncweaver-host-capsule
- repository: NIDAP-Community/MOSuite-create
- repository: NIDAP-Community/MOSuite-clean
- repository: NIDAP-Community/MOSuite-filter-counts
- repository: NIDAP-Community/MOSuite-normalize-counts
- repository: NIDAP-Community/MOSuite-batch-correct-counts
- repository: NIDAP-Community/MOSuite-diff-counts
- repository: NIDAP-Community/MOSuite-filter-diff
- repository: NIDAP-Community/MOSuite-plot-expr-heatmap
- repository: NIDAP-Community/MOSuite-plot-pca-2D
- repository: NIDAP-Community/MOSuite-plot-pca-3D
- repository: NIDAP-Community/MOSuite-plot-volcano-summary
- repository: NIDAP-Community/MOSuite-plot-venn-diagram
- repository: NIDAP-Community/MOSuite-write-moo-properties
