name: "docs"

on:
  schedule:
    - cron: "43 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "_quarto.yml"
      - "*.qmd"
      - "*.md"
      - ".github/workflows/docs-quarto.yml"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - name: git config
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "41898282+github-actions[bot]"

      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          activate-environment: true
          pixi-version: v0.75.0
          cache: true

      - uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        if: github.event != 'pull_request'
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ github.token }}
